export enum CompetencyCategory {
  COGNITIVE = 'COGNITIVE',
  INTERPERSONAL = 'INTERPERSONAL',
  LEADERSHIP = 'LEADERSHIP',
  ADAPTABILITY = 'ADAPTABILITY',
  EMOTIONAL_INTELLIGENCE = 'EMOTIONAL_INTELLIGENCE',
  COMMUNICATION = 'COMMUNICATION',
  COLLABORATION = 'COLLABORATION',
  CRITICAL_THINKING = 'CRITICAL_THINKING',
  TIME_MANAGEMENT = 'TIME_MANAGEMENT'
}
export enum ProficiencyLevel {
  NOVICE = 'NOVICE',
  DEVELOPING = 'DEVELOPING',
  PROFICIENT = 'PROFICIENT',
  ADVANCED = 'ADVANCED',
  EXPERT = 'EXPERT',
}

export enum ApprovalStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
  UNDER_REVISION = 'UNDER_REVISION'}

export enum IndicatorMeasurementType  {
  FREQUENCY = 'FREQUENCY',
  QUALITY = 'QUALITY',
  IMPACT = 'IMPACT',
  CONSISTENCY = 'CONSISTENCY',
  IMPROVEMENT = 'IMPROVEMENT',
}

export enum QuestionType {
  LIKERT_SCALE = 'LIKERT_SCALE',
  SITUATIONAL_JUDGMENT = 'SITUATIONAL_JUDGMENT',
  BEHAVIORAL_EXAMPLE = 'BEHAVIORAL_EXAMPLE',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  CAPABILITY_ASSESSMENT = 'CAPABILITY_ASSESSMENT',
  SELF_REFLECTION = 'SELF_REFLECTION',
  PEER_FEEDBACK = 'PEER_FEEDBACK',
  FREQUENCY_SCALE = 'FREQUENCY_SCALE',
  OPEN_TEXT = 'OPEN_TEXT',
}

export enum DifficultyLevel {
  FOUNDATIONAL = 'FOUNDATIONAL',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  EXPERT = 'EXPERT',
  SPECIALIZED = 'SPECIALIZED',
}