export enum CompetencyCategory {
  COGNITIVE = 'COGNITIVE',
  INTERPERSONAL = 'INTERPERSONAL',
  LEADERSHIP = 'LEADERSHIP',
  ADAPTABILITY = 'ADAPTABILITY',
  EMOTIONAL_INTELLIGENCE = 'EMOTIONAL_INTELLIGENCE',
  COMMUNICATION = 'COMMUNICATION',
  COLLABORATION = 'COLLABORATION',
  CRITICAL_THINKING = 'CRITICAL_THINKING',
  TIME_MANAGEMENT = 'TIME_MANAGEMENT'
}
export enum ProficiencyLevel {
  NOVICE = 'NOVICE',
  DEVELOPING = 'DEVELOPING',
  PROFICIENT = 'PROFICIENT',
  ADVANCED = 'ADVANCED',
  EXPERT = 'EXPERT',
}

export enum ApprovalStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
  UNDER_REVISION = 'UNDER_REVISION'}

export enum IndicatorMeasurementType  {
  QUALITY= 'QUALITY',
  QUANTITY= 'QUANTITY',
  FREQUENCY= 'FREQUENCY',
  BINARY= 'BINARY',
}

export enum QuestionType {
  MULTIPLE_CHOICE= 'MULTIPLE_CHOICE',
  SINGLE_CHOICE= 'SINGLE_CHOICE',
  TRUE_FALSE= 'TRUE_FALSE',
  OPEN_ENDED= 'OPEN_ENDED',
  SCENARIO_BASED= 'SCENARIO_BASED',
  LIKERT_SCALE= 'LIKERT_SCALE',
  SITUATIONAL_JUDGMENT= 'SITUATIONAL_JUDGMENT',
}

export enum DifficultyLevel {
  BASIC= 'BASIC',
  INTERMEDIATE= 'INTERMEDIATE',
  ADVANCED= 'ADVANCED',
  EXPERT= 'EXPERT',
}