export type CompetencyCategory =
	| "COGNITIVE"
	| "INTERPERSONAL"
	| "LEADERSHIP"
	| "ADAPTABILITY"
	| "EMOTIONAL_INTELLIGENCE"
	| "COMMUNICATION"
	| "COLLABORATION"
	| "CRITICAL_THINKING"
	| "TIME_MANAGEMENT";

export type ProficiencyLevel =
	| "NOVICE"
	| "DEVELOPING"
	| "PROFICIENT"
	| "ADVANCED"
	| "EXPERT";

export type ApprovalStatus =
	| "DRAFT"
	| "PENDING_REVIEW"
	| "APPROVED"
	| "REJECTED"
	| "ARCHIVED"
	| "UNDER_REVISION";

export type IndicatorMeasurementType =
	| "FREQUENCY"
	| "QUALITY"
	| "IMPACT"
	| "CONSISTENCY"
	| "IMPROVEMENT";

export type QuestionType =
	| "LIKERT_SCALE"
	| "SITUATIONAL_JUDGMENT"
	| "BEHAVIORAL_EXAMPLE"
	| "MULTIPLE_CHOICE"
	| "CAPABILITY_ASSESSMENT"
	| "SELF_REFLECTION"
	| "PEER_FEEDBACK"
	| "FREQUENCY_SCALE"
	| "OPEN_TEXT";

export type DifficultyLevel = 
	| "FOUNDATIONAL" 
	| "INTERMEDIATE" 
	| "ADVANCED" 
	| "EXPERT"
	| "SPECIALIZED";
